name: Ekadashi WP Uploader

on:
  workflow_dispatch:   # Allows manual trigger
  schedule:
    - cron: '0 0 1 1 *'  # Runs yearly on Jan 1 at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ekadashi Script
        env:
          WP_SITE: ${{ secrets.WP_SITE }}
          USERNAME: ${{ secrets.WP_USERNAME }}
          APP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          YEAR: '2025'
        run: python main.py
